name = "HMMDiscretization"
uuid = "39c49a46-f006-40e3-92b6-71c9dffd4e78"
version = "0.1.0"
authors = ["Zoltán Rácz"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Distributions = "0.25.122"
DocStringExtensions = "0.9.5"
LinearAlgebra = "1.10"
Parameters = "0.12.3"
Statistics = "1.10"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
